[package]
name = "fractal"
version = "0.1.0"
authors = ["Joshua Gerth <jgerth@hrakaroo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"
num-complex = "0.2.4"
